[project]
name = "magic-the-gathering-analyzer"
version = "0.1.0"
description = "Magic: The Gathering card analyzer"
requires-python = ">=3.13"
dependencies = [
    "dlt[duckdb,hub,workspace]",
]

[tool.uv]
package = false
